#server:
#  port: 8084
#  servlet:
#    context-path: '/ead-notification/'

spring:
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 'ead123cs'

#  datasource:
#    url: jdbc:postgresql://localhost:5435/ead-notification-v2
#    username: postgres
#    password: AdmPostgres@1991
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  output:
#    ansi:
#      enabled: Always #Deixa mais claro os outputs em terminais externos - coloridos
#  rabbitmq:
#    addresses: amqps://ddpwcyvf:w-ZgnBJihto7dEJlQ3knAqGDYkwCExTY@beaver.rmq.cloudamqp.com/ddpwcyvf
#
#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#
#ead:
#  broker:
#    exchange:
#      notificationCommandExchange: ead.notificationcommand
#    queue:
#      notificationCommandQueue:
#        name: ead.notificationcommand.ms.notification
#    key:
#      notificationCommandKey: ms.notification
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh, health